import { StyleSheet, Text, View } from 'react-native'
import React, { useEffect } from 'react'
import translate from 'translate-google-api';

type Props = {}

let data = {
  "yourServiceWasSuccessfulClickOnTrackRequestStatusToKnowMoreToAvailTheServiceAgainClickOnIMInterested": "Your service was successful. Click on track request status to know more. To avail the service again, click on I'm Interested",
  "yourInterestHasBeenNotedNowYouCanTrackTheProgressOfYourServiceRequest": "Your interest has been noted. Now you can track the progress of your service request",
  "yourSessionIsBookedForTheBelowDatesIsBeingReviewed": "Your session is booked for the below dates is being reviewed.",
  "ddressSCaretakerDetailsEtcLoremIpsumDolorSitAmet": "Address(s), Caretaker details, etc. lorem ipsum dolor sit amet,",
  "onsecteturAdipiscingElit": "consectetur adipiscing elit.",
  "pleaseTryAgain": "Please Try Again",
  "isUnderReview": "is under review",
  "sideEffectsOfTreatment": "Side Effects of Treatment",
  "treatmentStrategies": "Treatment Strategies",
  "treatmentForLiverCancer": "Treatment for Liver Cancer",
  "treatmentForLungCancer": "Treatment for Lung Cancer",
  "processCompleted": "Process completed",
  "processAborted": "Process aborted",
  "requestWas": "request was",
  "rejectedPleaseTryAgainClickBelowToCheckYourPreviousRequestStatus": "rejected , please try again. Click below to check your previous request status.",
  "loanHasBeenSuccessfullyDisbursed": "loan has been successfully Disbursed",
  "clickOnTrackRequestStatusToKnowMoreToAvailTheServiceAgainClickOnIMInterested": "Click on track request status to know more. To avail the service again, click on I'm Interested",
  "thisBoxTo": "this box to",
  "optIn": "Opt in",
  "andStartReceivingTheBlueTreeAppSmsNotifications": "and start receiving the Blue Tree App SMS notifications.",
  "untick": "Untick",
  "optOut": "Opt out",
  "andStopReceivingTheBlueTreeAppSmsNotifications": "and stop receiving the Blue Tree App SMS notifications.",
  "pleaseSelectAtleastOneMedicine": "Please select atleast one medicine",
  "pleaseEnterRefDoctor": "Please enter ref doctor",
  "pleaseEnterValidDocName": "Please enter valid doc name",
  "pleaseEnterValidDoctorName": "Please enter valid doctor name",
  "profileUpdatedSuccessfully": "Profile Updated Successfully",
  "uploadDocumentsToGetYourselvesEnrolledForTheTbtProgram": "Upload documents to get yourselves enrolled for the TBT Program.",
  "eWillBeReviewingYourDocumentsAndIfNeededWeShallReach": "We will be reviewing your documents and if needed, we shall reach",
  "utToYou": "out to you.",
  "toGetTheFocVialsFromLoremWeWouldLikeToKnowYour": "To get the FOC Vials from Lorem, we would like to know your",
  "dispatchAddress": "Dispatch Address",
  "help": "Help",
  "photoSizeCannotBeGreaterThan4Mb": "Photo size cannot be greater than 4 MB",
  "documentSizeCannotBeGreaterThan4Mb": "Document size cannot be greater than 4 MB",
  "sorrySampleDocumentLinkNotAvailable": "Sorry , Sample document link not available",
  "pleaseUpdateYourProfileTo100%BeforeUploadingDocument": "Please update your profile to 100% before uploading document",
  "noServicesAvailableAtThisTime": "No Services Available at this time",
  "noDocumentsAvailableAtThisTime": "No Documents Available at this time",
  "pleaseFillTheMandatoryDetailsFirst": "Please fill the mandatory details first.",
  "terms&#038;Conditions": "Terms & Conditions",
  "privacyPolicy": "Privacy Policy",
  "optInSms": "Opt-in SMS",
  "please": "Please",
  "tick": "Tick",
  "freeVials": "2 Free Vials",
  "paidVials": "1 Paid Vials",
  "infusionSummary": "Infusion summary",
  "youDonTHaveAnyRequestedStatus": "You don't have any Requested status",
  "selectLanguage": "Select language",
  "welcomeToTbtProgram": "Welcome to TBT program!",
  "yourContactHasNotBeenEstablished": "Your Contact has not been Established.",
  "youHaveNotExpressedInterestInJoiningACrowdfundingCampaign": "You have not expressed interest in joining a crowdfunding campaign.",
  "noSlotsAvailableForThisDate": "No Slots available for this date",
  "pleaseSelectDateToSelectTimeslot": "Please Select date to select timeslot",
  "pleaseCheckYourInternetConnectivityAndTryAginAfterSomeTime": "Please check your internet connectivity and try agin after some time.",
  "dateOfBirth": "Date Of Birth",
  "address": "Address",
  "others": "Others",
  "years": "years",
  "next": "Next",
  "hi": "Hi,",
  "searchHospitals": "Search Hospitals",
  "submit": "Submit",
  "fileMoreThan10MbCannotBeUploaded": "File more than 10 MB cannot be uploaded",
  "therapyOn": "Therapy on",
  "noTrackingLinkIsAvailableAtThisTime": "No Tracking Link is available at this time",
  "toBeDispatched": "To Be Dispatched",
  "dispatched": "Dispatched",
  "trackMyOrder": "Track my order",
  "delivered": "Delivered in:",
  "quantity": "Quantity",
  "shareChallenge": "Share challenge",
  "sendLink": "Send link",
  "sendLinkPressed": "Send link pressed",
  "shareToSocial": "Share to social",
  "sharedToSocialPressed": "Shared to social pressed",
  "ghostLink": "Ghost link",
  "youCannotSelectTodaysDate": "You Cannot select todays date",
  "getStarted": "Get Started",
  "searchDoctors": "Search Doctors",
  "updateRequired": "Update Required:",
  "thereIsANewVersionAvailableForDownloadPleaseUpdateTheAppAtTheEarliest": "There is a new version available for download! Please update the App at the earliest.",
  "update": "Update",
  "male": "Male",
  "female": "Female",
  "pendingInformation": "Pending information",
  "save": "Save",
  "home": "Home",
  "pleaseEnterValidAddress": "Please enter valid Address",
  "pleaseEnterAddress": "Please enter Address",
  "pleaseEnterValid6DigitsPin": "Please enter valid 6 digits PIN",
  "pleaseEnterPin": "Please enter PIN",
  "addressLine1": "Address line 1",
  "addressLine2": "Address line 2",
  "state": "State",
  "city": "City",
  "pin": "PIN",
  "demo": "Demo",
  "pressMe": "Press me",
  "edit": "Edit",
  "photoSize": "Photo size cannot be greater than 4 MB",
  "amicar": "Amicar (Epsilon Amino Caproic Acid)",
  "amicarDesc": "prevents blood clots from breaking down, resulting in a firmer clot. It is often used for bleeding in the mouth or after a tooth has been removed because it blocks a substance found in the saliva (spit) that breaks down clots.",
  "factorLevel": "Factor Level",
  "whatExpect": "What to Expect",
  "subText1": "Occur usually after an injury, trauma, or surgery,including \ndental procedures",
  "subText2": "Bleeding after minor injuries",
  "subText3": "Spontaneous bleeding without \n an obvious cause may occur,\n but it is rare",
  "subText4": "Bleeding after injury, trauma or surgery",
  "subText5": "Spontaneous bleeding into \n joints and muscles",
  "moderate": "Moderate\nHemophilia",
  "severe": "Severe \nHemophilia",
  "episodicCareDesc2": "Increased risk of joint damage",
  "episodicCareDesc3": "Increased risk of spontaneous bleeds",
  "prophylacticCare": "Prophylactic Care",
  "prophylacticCareDesc": "Most cases of hemophilia are severe and need preventative treatment involving regular injections of clotting factor medicine. This is called preventive or prophylactic therapy, the primary treatment for hemophilia. Concentrates of clotting factor VIII (for hemophilia A) or clotting factor IX (for hemophilia B) are slowly dripped or injected into a vein. These infusions help replace the clotting factor thats missing or low.\n\nThe two main types of clotting factor concentrates available are:",
  "plasma": "Plasma-derived Factor",
  "plasmaDesc": "Plasma is the liquid part of blood containing proteins such as antibodies, albumin, and clotting factors. Several factor concentrate treatment products are available that are made from human plasma proteins. The clotting proteins are then made into a freeze-dried product, which is tested and treated to kill any potential viruses before it is packaged for use.",
  "recombinantFactor": "Recombinant Factor",
  "recombinantFactorDesc": "Non-human plasma concentrate, genetically engineered using DNA technology. Commercially prepared factor concentrates are treated to remove or inactivate bloodborne viruses. Recombinant factors VIII (8) and IX (9) do not contain any plasma or albumin, and therefore, cannot spread any bloodborne viruses.",
  "recombinantFactorDesc1": "Hemlibra (emicizumab), the new non-factor replacement therapy to manage hemophilia. It works by replacing the function of factor VIII (8) rather than directly replacing the missing clotting factor VIII (8).\nAs a result, it can prevent or reduce the frequency of bleeding episodes in people with hemophilia A.",
  "DDAVP": "DDAVP or Stimate (Desmopressin Acetate)",
  "DDAVPDesc": "is similar to a hormone that occurs naturally in the body, the medications release factor VIII (8) from where it is stored in the body tissues. For people with mild, as well as some cases of moderate, this can work to increase factor VIII (8) levels so that they do not have to use clotting factors to stop bleeding episodes.",
  "hemoSeotDesc": "Antibodies can destroy the clotting factor before it has a chance to work. A severe problem that prevents the primary treatment for hemophilia (replacement therapy) from working.\n\nWhen antibodies develop, doctors may use larger doses of clotting factor or try different clotting factor sources. Sometimes the antibodies go away.",
  "hemoSeotTitle1": "Viral Infection from clotting factors",
  "hemoSeotDesc1": "Clotting factors from human blood can carry the viruses that cause HIV/AIDS and hepatitis. However, the risk of getting an infectious disease from human clotting factors is minimal due to the following:",
  "hemoSeotTitle2": "Careful screening of blood donors",
  "hemoSeotTitle3": "Testing of donated blood products",
  "hemoSeotTitle4": "Treating donated blood products with a detergent and heat to destroy viruses",
  "hemoSeotTitle5": "Vaccinating people who have hemophilia for hepatitis A and B",
  "episodicCare": "Episodic Care",
  "episodicCareDesc": "In mild or moderate cases, hemophilia treatment may only be necessary as an immediate response to bleeding. Episodic or on-demand treatment is used to treat an active bleed. Factor VIII (8) is infused after an injury or a bleed has started.\n\nPossible advantages of on-demand treatment include the following:",
  "fewerinfusions": "Fewer infusions",
  "lowercost": "Lower cost",
  "episodicCareDesc1": "Possible disadvantages of on-demand treatment include the following:",
  "treatmentComplications2": "Bleeding into a joint. If this happens many times, it can lead to changes in the joints shape and impair its function.",
  "treatmentComplications3": "Swelling of the membrane around a joint.",
  "treatmentComplications4": "Pain, swelling, and redness of a joint.",
  "treatmentComplications5": "Pressure on a joint from swelling, which can destroy the joint.",
  "treatmentComplications6": "Side effects of Treatment",
  "treatmentComplications7": "Hemophilia treatments were accompanied by severe complications in the past, resulting in significant morbidity and mortality. However, current products are much safer. Yet there are some known side effects of treatment for replacement therapy.",
  "treatmentComplications8": "Antibodies that attack clotting factor",
  "treatmentComplications9": "Viral Infections from clotting factor",
  "hemoSeotTitle": "Antibodies that attack the clotting factor",
  "lifecycle44": "Get vaccinations.",
  "lifecycle4": "People with hemophilia should receive recommended vaccinations at the appropriate ages, as well as hepatitis A and B.",
  "lifecycle55": "Protect your child from injuries that cause bleeding.",
  "lifecycle5": "Knee pads, elbow pads, helmets, and safety belts all help prevent injuries from falls and other accidents. Keep your home free of furniture with sharp corners.",
  "hemophiliaTreatments": "Hemophilia Treatments",
  "hemophiliaTreatmentsDes": "The best way to treat hemophilia is to replace the missing blood clotting factor so that the blood can clot properly. This is typically done by injecting treatment products, called clotting factor concentrates, into a person’s vein. Newer non-factor replacement therapies are now available, which are given through under-the-skin injections.\n\nThere are three main treatment strategies for hemophilia:",
  "hemophiliaTreatmentsTyep1": "Episodic Care\n\nStops a patient’s bleeding episodes",
  "hemophiliaTreatmentsTyep2": "Prophylactic Care\n\nPrevents bleeding episodes",
  "hemophiliaTreatmentsTyep3": "Management with Medicines",
  "Inhibitors": "Inhibitors",
  "InhibitorsDesc": "About 15-20% of people with hemophilia develop an antibody (called an inhibitor) that stops the clotting factors from being able to clot the blood and stop bleeding. Treatment of bleeding episodes becomes tough, and the cost of care for a person with an inhibitor can skyrocket because more clotting factors or a different type of clotting factor is needed. People with inhibitors often experience more joint disease and other problems from bleeding that result in a reduced quality of life.3",
  "treatmentComplications": "Complications from Treatment",
  "treatmentComplications1": "Delays in treatment can cause damage, such as:",
  "hemoPhy4": "Enhance core muscle strength and improve posture to improve balance",
  "hemopsy1": "To promote adjustment to the condition, psychological counselling can help patients cope with the various stressors linked to their disease. Family members who sometimes fail to cope with health complications can also benefit from these sessions. A mental health expert can help:",
  "hemopsy2": "Express emotions in a healthy way",
  "hemopsy3": "Stay engaged with self-management",
  "hemopsy4": "Focus on positive health outcomes",
  "hemopsy5": "Stay connected with family and friends",
  "hemopsy6": "Integration of psychosocial care is of crucial importance in the management of hemophilia. It could help patients and caregivers cope with the difficulties by stimulating their coping mechanisms.",
  "lifecycle11": "Avoid certain pain medications.",
  "lifecycle1": "Drugs that can make bleeding worse include aspirin and ibuprofen. Instead, use acetaminophen, a safer alternative for mild pain relief.",
  "lifecycle22": "Avoid blood-thinning medications.",
  "lifecycle2": "Medications that prevent blood from clotting include heparin, warfarin, clopidogrel, prasugrel, ticagrelor, rivaroxaban, apixaban, edoxaban, and dabigatran.",
  "lifecycle33": "Practice good dental hygiene.",
  "lifecycle3": "The goal is to prevent tooth and gum disease, which can lead to excessive bleeding.",
  "hemophiliaNutri1": "Taking charge of your health when you have hemophilia is very important. Regardless of your hemophilia type, with the right diet, you can:",
  "hemophiliaNutri2": "Keep joints strong and healthy",
  "hemophiliaNutri3": "Keep extra weight off to avoid muscle strains and bleeding in joints",
  "hemophiliaNutri4": "Maintaining iron levels",
  "hemophiliaNutri5": "Enhance iron absorption by the body",
  "hemophiliaNutriDes": "Consume dark, leafy greens and orange fruits and vegetables are very good sources of vitamins and minerals. \n\nGrains consumption should have oats, barley, whole wheat, bran, and brown rice. \n\nSkimmed milk or low-fat curd and paneer are good sources of vitamins and minerals as well as calcium, without the unnecessary fats.\n\nReducing portion sizes, learning to read labels and avoiding “easy snacks” – high-fat foods generally offer low-to-zero nutritional value.",
  "hemophiliaNutri6": "Keep joints strong and healthy",
  "hemophiliaNutri7": "Keep extra weight off to avoid muscle strains and bleeding in joints",
  "hemophiliaNutri8": "Maintaining iron levels",
  "hemophiliaNutri9": "Enhance iron absorption by the body",
  "hemophiliaGuidance": "Guidelines",
  "physioDes": "Hemophilia is a rare disorder that is complex to diagnose and to manage. Optimal care of patients, especially those with severe forms of the disease, requires a multidisciplinary team of healthcare professionals with expertise and experience to attend to the physical and psychosocial health of patients and their families. Management can be classified into the following:",
  "hemoPhy1": "Physiotherapy is an essential part of hemophilia management as it helps repair injured muscles, build strength, decrease pain and swelling, and increase the patient’s movement and range of motion, when performed correctly and under the guidance of a trained expert. A personalised schedule will help:",
  "hemoPhy2": "Build muscle strength to protect and support the joints lowering the risk of bleeding episodes",
  "hemoPhy3": "Address specific areas of weakness to improve fitness and prevent bleeds",
  "range3": "<1%",
  "mildHemophilia": "Mild \nHemophilia",
  "mainHemophiliaDescription": "Hemophilia is a rare disorder that is complex to diagnose and to manage. Optimal care of patients, especially those with severe forms of the disease, requires a multidisciplinary team of healthcare professionals with expertise and experience to attend to the physical and psychosocial health of patients and their families. Management can be classified into the following:",
  "phy1": "Physiotherapy is an essential part of hemophilia management as it helps repair injured muscles, build strength, decrease pain and swelling, and increase the patient’s movement and range of motion, when performed correctly and under the guidance of a trained expert. A personalised schedule will help:",
  "phy2": "Build muscle strength to protect and support the joints lowering the risk of bleeding episodes",
  "phy3": "Address specific areas of weakness to improve fitness and prevent bleeds",
  "phy4": "Enhance core muscle strength and improve posture to improve balance",
  "phy5": "Reduce stiffness, increase joint movement, and build muscle strength",
  "psy1": "To promote adjustment to the condition, psychological counselling can help patients cope with the various stressors linked to their disease. Family members who sometimes fail to cope with health complications can also benefit from these sessions. A mental health expert can help:",
  "psy2": "Express emotions in a healthy way",
  "psy3": "Stay engaged with self-management",
  "psy4": "Focus on positive health outcomes",
  "psy5": "Stay connected with family and friends",
  "psy6": "Integration of psychosocial care is of crucial importance in the management of hemophilia. It could help patients and caregivers cope with the difficulties by stimulating their coping mechanisms.",
  "type1Hemophilia": "Hemophilia A \n(Classic Hemophilia)",
  "type2Hemophilia": "Hemophilia B \n(Christmas Disease)",
  "type3Hemophilia": "Severity of Hemophilia",
  "typesDes": "There are several different types of hemophilia. The following two are the most common:",
  "typesTitleHemophilia": "Types of Hemophilia",
  "differentHemophilia": "Different types of hemophilia",
  "typeAdesc": "This type is caused by a lack or decrease of clotting factor VIII (8).",
  "typeBdesc": "This type is caused by a deficiency of clotting factor IX (9).",
  "severityHeader": "Severity of Hemophilia",
  "lifestyle": "Lifestyle and Home Remedies",
  "severity": "Severity",
  "severityDesc": "The severity of hemophilia that a person has is determined by the number of factors in the blood. The lower the factor, the more likely it is that bleeding will occur, leading to serious health problems.\n\nHemophilia can be mild, moderate, or severe, depending on how much of the clotting factor is in the blood. A healthy persons normal range of factor VIII and factor IX is between 50% and 150%.",
  "range1": ">5% to <40%",
  "range2": "1% to 5%",
  "type2nonhodgkinLymphomaDesc": "Appears in many lymph nodes throughout the body and the bone marrow. Often slow-growing, this subtype can be treated but is difficult to cure. Depending on certain factors, treatment may be delayed until the disease grows or the person has symptoms. When needed, treatment is often effective. It may lead to a period of remission (when all signs of your cancer are gone), after which cancer returns. In 25-60 percent of people with FL, their disease eventually becomes a more aggressive large-cell lymphoma. This usually does not happen until sometime after diagnosis, often years later.",
  "type3nonhodgkinLymphomaDesc": "T-cell lymphomas Are less common but can be aggressive (fast-growing) or indolent (slow-growing). Common subtypes of T-cell lymphomas include:",
  "nonHodgkinLymphomasubType1": "Peripheral T-cell lymphoma, not otherwise specified (PTCL-NOS)",
  "nonHodgkinLymphomasubType2": "Cutaneous T-cell lymphoma (Sézary syndrome and mycosis fungoides)",
  "nonHodgkinLymphomasubType3": "Anaplastic large cell lymphoma",
  "nonHodgkinLymphomasubType4": "Angioimmunoblastic T-cell lymphoma",
  "myelomaTypeDesc": "a cancer of the plasma cells. Plasma cells are white blood cells that produce disease- and infection-fighting antibodies in your body. Myeloma cells prevent the normal production of antibodies, leaving your bodys immune system weakened and susceptible to infection.\n\nMyeloma cells are produced in the bone marrow, the soft tissue inside your bones. Sometimes myeloma cells will travel through your bloodstream and collect in other bones in your body. Because myeloma frequently occurs at many sites in the bone marrow, it is often referred to as multiple myeloma.",
  "hemophilia": "Hemophilia",
  "understandingHemophilia": "Understanding Hemophilia",
  "treatmentHemophilia": "Treatment for Hemophilia",
  "mangingHemophilia": "Managing Hemophilia",
  "whatsHemophilia": "What is Hemophilia?",
  "hemophiliaDes": "Hemophilia is an inherited bleeding disorder in which the blood does not clot properly, leading to spontaneous bleeding and bleeding following injuries or surgery. Blood contains many proteins called clotting factors that can help to stop bleeding. People with hemophilia have low levels of either factor VIII (8) or factor IX (9).",
  "typesHemophilia": "Types of Hemophilia:",
  "subType5Desc": "Hodgkin Lymphoma",
  "subType6Desc": "Non-Hodgkin Lymphoma",
  "typesLymphoma": "Types of Lymphoma",
  "hodgkinLymphoma": "Hodgkin Lymphoma",
  "hodgkinLymphomaDesc": "The World Health Organisations (WHO) classification system puts Hodgkin lymphoma into 2 main groups. They are:",
  "type1hodgkinLymphoma": "Classical Hodgkin lymphoma (CHL)",
  "type2hodgkinLymphoma": "Nodular Lymphocyte predominant type Hodgkins Lymphoma (NLPHL)",
  "type1hodgkinLymphomaDesc": "It is the most common form of Hodgkin lymphoma. There are 4 subtypes, and they all contain abnormal cells called Reed-Sternberg cells. These cells are a type of white blood cell (B lymphocyte) that have become cancerous. The subtypes include Nodular sclerosing, Mixed cellularity, lymphocytes rich, and lymphocytes depleted.",
  "type2hodgkinLymphomaDesc": "This type of Hodgkin lymphoma is often only in one lymph node group when diagnosed (localised disease). It tends to grow slower than classical Hodgkin lymphoma, and the treatment is different.",
  "nonHodgkinLymphoma": "Non-Hodgkin Lymphoma",
  "nonHodgkinLymphomaDesc": "There are about 60 different subtypes, and most fall into two main groups named from the cell where the lymphoma starts: B-cell lymphomas or T-cell lymphomas. B-cell lymphomas comprise most cases and are either Diffuse Large B-cell lymphoma (DLBCL) or Follicular Lymphoma (FL).",
  "type1npnhodgkinLymphoma": "Diffuse Large B-cell lymphoma (DLBCL)",
  "type2npnhodgkinLymphoma": "Follicular Lymphoma (FL)",
  "type3npnhodgkinLymphoma": "T-cell lymphomas",
  "type1nonhodgkinLymphomaDesc": "Usually starts as a quickly growing mass in a lymph node in the chest or abdomen or in a lymph node you can feel, such as the neck or armpit. It can grow in other areas such as the intestines, bone, brain, or spinal cord. Although this is a fast-growing lymphoma, DLBCL usually responds well to treatment. It can sometimes be cured entirely with chemotherapy.",
  "lymphoma": "Lymphoma",
  "myeloma": "Myeloma",
  "bloodCancer": "Blood Cancer",
  "understandingBloodC": "Understanding Blood Cancer",
  "treatmentBloodC": "Treatment for Blood Cancer",
  "typesofBloodC": "Types of Blood Cancer",
  "type1Desc": "A type of cancer found in your blood and bone marrow, is caused by the rapid production of abnormal white blood cells. The high number of abnormal white blood cells cannot fight infection, and they impair the ability of the bone marrow to produce red blood cells and platelets.\n\nLeukemia can be either acute or chronic. Chronic leukemia progresses more slowly than acute leukemia, which requires immediate treatment. There are four broad classifications of leukemia:",
  "type2Desc": "Leukemia occurs in both adults and children. ALL is the most common form of childhood leukemia, and AML is the second most common.",
  "subType1Desc": "Acute lymphocytic leukemia (ALL)",
  "subType2Desc": "Acute myelogenous leukemia (AML)",
  "subType3Desc": "Chronic lymphocytic leukemia (CLL)",
  "subType4Desc": "Chronic myelogenous leukemia (CML)",
  "type3Desc": "A type of blood cancer that affects the lymphatic system, which removes excess fluids from your body and produces immune cells. Lymphocytes are a type of white blood cell that fights infection. Abnormal lymphocytes become lymphoma cells, which multiply and collect in your lymph nodes and other tissues. Over time, these cancerous cells impair your immune system.\n\nLymphomas are divided into two categories depending on certain unique characteristics of the different lymphoma cells:",
  "type4Description": "Non-Hodgkin lymphoma is much more common than Hodgkin lymphoma and is B-cell lymphoma that either multiply (high-grade) or develops slowly (low-grade). The rest are T-cell lymphomas, named after a different cancerous white blood cell or lymphocyte.\n\nMany lymphoma patients can lead active lives as they receive treatment for their symptoms and are monitored by their doctors.",
  "psychology4": "Openly discuss your emotions, fears, and frustrations",
  "psychology5": "Help with medications to treat clinical depression if required",
  "psychology6": "Prioritizing your mental health is equally as important as caring for your physical health while dealing with breast cancer. Talk to a mental health expert to find effective strategies that help you deal with confusing emotions. This service is available to you free of cost.",
  "bloodCTreatmentTitle": "Treatment for Blood Cancer",
  "bloodTreatmentDesc": "There is a range of different treatments available for blood cancer. The treatment your doctors recommend depends on your type of blood cancer, cell type, biomarker testing results, and health. You might have a kind of treatment or a number of them.",
  "bloodSeotDesc": "Cancer treatments can sometimes be challenging, causing your physical and emotional health to go through ups and downs. It takes time to heal from the side effects altogether. However, various nutritional and dietary tips are available to deal with these side effects. \n\n Here are some common and simple tips for dealing with the side effects of cancer treatments:",
  "bloodManagingTitle": "Managing Blood Cancer",
  "bloodManagingDescription": "You can manage blood cancer with the help of suitable medication, diet, and physiotherapy. Apart from these, taking care of your mental and emotional health is also essential. It can support your treatment and help you feel better physically.",
  "bloodUnderstandingTitle": "Understanding Blood Cancer",
  "whatsBloodC": "What is Blood Cancer?",
  "bloodUnderstandingDesc": "Blood cancers affect the production and function of your blood cells. Most of these cancers start in your bone marrow, where blood is produced. Stem cells in your bone marrow mature and develop into three types of blood cells: red blood cells, white blood cells, or platelets. In most blood cancers, the normal blood cell development process is interrupted by the uncontrolled growth of an abnormal type of blood cell.\n\nThese abnormal or cancerous cells prevent your blood from performing many functions, like fighting off infections or preventing serious bleeding.",
  "bloodTypesTitle": "Types of Blood Cancer:",
  "leukemia": "Leukemia",
  "nutri12": "Guideline",
  "nutri13": "Keep body tissues healthy and maintains a healthy body weight.",
  "guidelines": "Guidelines",
  "nutri10": "Avoid alcohol when undergoing treatment and even after the treatment. Beer, wine, or liquor may interact with cancer drugs. Alcohol also increases the risk of cancer recurrence.Spicy, oily, high-fat food is difficult to digest – avoid them.\n\n Don’t eat fast food like pizzas, fries, and burgers.\n\nDairy products are also heavy to digest. Say not to organ meats or anything that has unhealthy fats.\n\nTo avoid complications, don’t eat undercooked food. It may cause infections. Always eat food that is cooked at a safe temperature.\n\nDon’t consume leftovers, expired food, etc., and avoid processed food, sugar-sweetened beverages like cold drinks and too many cups of tea or coffee.",
  "nutri11": "Keep body tissues healthy and maintains a healthy body weight.",
  "physio1": "Exercise is an integral part of a cancer treatment plan. Regular exercise can significantly improve physical and mental health during every phase of treatment. A regular and personalized schedule can help you:",
  "physio2": "Improve",
  "physio3": "Reduce",
  "breastNutriDes": "A breast cancer diagnosis can be distressing and cause emotions of shock, anxiety, anger, sadness, and confusion. Along with the physical impacts of cancer, side effects of treatment, fear of recurrence, and changes to identity can aggravate mental health conditions. A mental health expert can help you manage these feelings. Here’s how sessions with a counsellor can help:",
  "physio4": "Talk to a physiotherapist to find a suitable plan that works for you. Even if you were not active before your cancer diagnosis, an exercise program that meets your specific needs could help you get moving safely and successfully. This service is available to you free of cost.",
  "psychology1": "A breast cancer diagnosis can be distressing and cause emotions of shock, anxiety, anger, sadness, and confusion. Along with the physical impacts of cancer, side effects of treatment, fear of recurrence, and changes to identity can aggravate mental health conditions. A mental health expert can help you manage these feelings. Here’s how sessions with a counsellor can help:",
  "psychology2": "Reduce stress and manage anxiety and improve mood",
  "psychology3": "Stay active, productive, and connected with family and friends",
  "treatmentStragiesDesc": "After verifying all the above factors, a patient may receive one or more of the following treatments:",
  "seotTitle": "Side Effects of Treatment",
  "seotDesc": "Cancer treatments can sometimes be challenging, causing your physical and emotional health to go through ups and downs. It takes time to heal from the side effects altogether. However, various nutritional and dietary tips are available to deal with these side effects – speak to your nutritional counsellor to get customised diet plans.",
  "mainDescription": "You can manage lung cancer with the help of suitable medication, diet, and physiotherapy. Apart from these, taking care of your mental and emotional health is also essential. It can support your treatment and help you feel better physically.",
  "nutritionalGuidance": "Nutritional Guidance",
  "psychologicalSupport": "Psychological Support",
  "nutri1": "A proper diet and nutrition plan will heal you and help you deal with the treatment. Here’s why it is crucial to eat well.",
  "nutri2": "Stay energized and heal faster",
  "nutri3": "Cope with the medication and the treatment",
  "nutri4": "Naturally boost your immune system and build strength to decrease fatigue.",
  "nutri5": "Reduces the risk of cancer recurrence.",
  "nutri6": "Talk to a nutritional expert to find a suitable diet that works for you. Seek information about the meal plan and how it can benefit you before you start your diet. This service is available to you free of cost.\n\nTo maintain a consistent diet, here is what you should and shouldn’t eat:",
  "nutri7": "Food you should eat",
  "nutri8": "Include a good amount of fruits and vegetables in your daily diet. Choose fresh fruits and vegetables.\n\n Eat high-fibre food like whole grains, flax seeds, oats etc. You can include whole-wheat bread, and brown rice.\n\nTo maintain a healthy weight, you can eat healthy fats and proteins. For example, nuts, seeds, and olive oil offer healthy fats.\n\nProtein-enriched food will boost your energy. If you eat non-veg, you can eat chicken, fish, and eggs for protein. Otherwise, legumes and lentils are fantastic sources of protein.",
  "nutri9": "Food you should not eat",
  "stage2Desc": "Stage II lung cancer has two subtypes.",
  "stage2SubDesc1": "Stage IIA: tumour is 4 to 5cm in size and has not spread into nearby lymph nodes.",
  "stage2SubDesc2": "Stage IIB: tumour is 5cm. In this stage, the tumour might have spread into lymph nodes within the lungs or the tumour is more than 5cm wide.",
  "stage3Desc": "Stage III cancer has three subtypes: IIIA, IIIB, and IIIC. Each stage indicates the specific size of the tumour and which lymph nodes are affected by cancer cells. In this stage, the cancer cells have not affected other distant organs.",
  "stage4Desc": "Stage IV is aggressive in nature. It indicates that cancer has spread into more than one part of the lungs, the fluid surrounding the lung or heart, or distant organs of the body through the bloodstream. Distant affected organs can be the brain, bones, liver, or adrenal glands.",
  "limitedStage": "Limited Stage",
  "limitedStageDesc": "It is a localized stage in which the cancer is in one place. It has not spread to nearby lung tissues or outer body parts. It is also called in situ lung cancer.",
  "extensiveStage": "Extensive Stage",
  "extensiveStageDesc": "It is a widely spread cancer throughout the lung, to other lung, lymph nodes, sides of the chest, or other body parts. It may also spread to the fluidaround the lung.",
  "lCTreatment": "Lung Cancer Treatments",
  "lCTreatmentDesc": "A healthcare team evaluates numerous conditions to determine the right treatment. In most cases, lung cancer treatment can be a combination of one or more therapies. \n\nThe factors that define lung cancer treatment are:",
  "treatmentStragiesTitle": "Treatment Strategies",
  "headerTypesLC": "Types of Lung Cancer",
  "SCLCDes": "It originates from small hormone-releasing cells and spreads aggressively. Unfortunately, it gets detected only after the spread, which makes it challenging to treat.\n\nIt has two subtypes:",
  "limited": "Limited",
  "limitedDesc": "Spreads on one side of the chest and in small areas.",
  "extensive": "Extensive",
  "extensiveDesc": "Spreads throughout the lung, to other lung, to lymph nodes on the other side of the chest, or to other body parts.",
  "SCLCStageTitle": "Small-Cell Lung Cancer Stages",
  "SCLCStageDesc1": "Small-Cell lung cancer is aggressive in nature, spreads faster and may affect distant organs. Instead of five stages, SCLC is categorized into two stages.",
  "SCLCTitle": "SCLC Cancer Stages",
  "SCLCStageDesc": "Small-Cell lung cancer is aggressive in nature, spreads faster and may affect distant organs. Instead of five stages, SCLC is categorized into two stages.",
  "NSCLCStage": "Non-Small Cell Lung Cancer Stages",
  "NSCLCStageDesc": "NSCLC has zero (0) to four (IV) stages. Each stage describes the size/location of the tumour and whether it has spread into lymph nodes or other body parts.",
  "stage0Desc": "Localized stage in which the cancer is in one place. It has not spread to nearby lung tissues or outer body parts. It is also called in situ lung cancer.",
  "stage1Desc": "Small cancer tumour that has not spread into any lymph nodes. The size of the tumour further divides stage I into IA and IB. \n\n Stage IA: 3cm or less in size \n\nStage IB: 3 to 4cm in size",
  "NSLCDesc": "Most commonly occurring cancer occurring in almost 80 to 85% of lung cancers cases.\n\nIt has three main subtypes:",
  "adenocarcinomaTilte": "Adenocarcinoma",
  "adenocarcinomaDesc": "Adenocarcinoma usually occurs in the outer parts of the lungs in the cells that secrete mucus-like substances. Therefore, it can be detected before it spreads.",
  "SquamousCellTitle": "Squamous Cell Carcinoma",
  "SquamousCellDesc": "Squamous Cell Carcinoma starts in squamous cells that line the inside of the airways in the lungs. This type of cancer is often found in the central parts of the lung.",
  "LargeCellTitle": "Large Cell Carcinoma",
  "LargeCellDesc": "Large Cell Carcinoma may begin and spread in any part of the lung. It spreads faster and can be challenging to treat.",
  "NSCLCStagesTitle": "Non-Small Cell Lung Cancer Stages",
  "NSCLCStagesDesc": "NSCLC has zero (0) to four (IV) stages. Each stage describes the size/location of the tumour and whether it has spread into lymph nodes or other body parts.",
  "stage0": "Stage 0",
  "stage1": "Stage 1",
  "stage2": "Stage 2",
  "stage3": "Stage 3",
  "stage4": "Stage 4",
  "smaPsy1": "Managing SMA can take a toll on one’s mental health. Experiencing symptoms that do not go away can result in feeling angry, depressed, frustrated, and more. It is not uncommon for individuals coping with SMA to also deal with anxiety and/or depression. A mental health expert can also provide helpful strategies and activities when feeling overwhelmed.",
  "smaPsy2": "Reduce stress and manage anxiety and improve mood",
  "smaPsy3": "Manage depression and mood",
  "smaPsy4": "Manage disordered eating and healthy body image",
  "smaPsy5": "Reduce feelings of isolation and loneliness",
  "lC": "Lung Cancer",
  "understandingLC": "Understanding Lung Cancer",
  "treatmentLC": "Treatment for Lung Cancer",
  "managingLC": "Managing Lung Cancer",
  "knowLC": "Understanding Lung Cancer",
  "whatisLC": "What is Lung Cancer?",
  "lCDes": "Lung Cancer is a type of disease in which cells/tissues in the lungs abnormally grow out of control. It may result in a tumour.\n\nOur right lung has 3 sections called lobes, and the left one has 2. The air breathed through the nose/mouth goes into the lungs via the trachea (windpipe). The windpipe further divides into bronchi and bronchioles tubes and gets connected to the tiny air sacs called alveoli.\n\nLung cancer usually begins in the cells lining the bronchi, bronchioles, or alveoli.",
  "typesofLC": "Types of Lung Cancer:",
  "NSCLC": "Non-Small Cell Lung Cancer\n(NSCLC)",
  "SCLC": "Small-Cell Lung Cancer\n(SCLC)",
  "smaPhy3": "Preventing soft tissue shortening",
  "smaPhy4": "Improving posture in lying, sitting, and standing",
  "smaPhy5": "Maximising respiratory function",
  "smaPhy6": "Maintaining muscle strength to delay muscle wastage",
  "smaPhy7": "Improving the quality of life",
  "smaPhy8": "Depending on the respiratory function, muscle power, range of movement, and functional ability of a patient, a treatment programme may involve:",
  "smaPhy9": "Stretching to lengthen tight muscles",
  "smaPhy10": "Correcting and varying posture in static and dynamic activities to promote symmetry and comfort",
  "smaPhy11": "Passive and active range of movement to increase joint flexibility and maintain muscle strength",
  "smaPhy12": "Breathing to reduce the risk of chest infections",
  "smaPhy13": "Hydrotherapy to stretch and strengthen muscles",
  "smaPhy14": "Advice on orthotics to help reduce deformities and position the foot while sleeping or when standing and walking.",
  "smaPhy15": "Advice about equipment to help with mobility, such as walking frames and wheelchairs",
  "smaNutri3": "Better breathing",
  "smaNutri4": "Lower risk of illness",
  "smaNutri5": "Better quality of life",
  "smaNutri6": "However, maintaining a balanced diet is not easy for people with SMA. Muscle weakness causes a range of problems that affect feeding and nutrient intake. People with SMA may experience:",
  "smaNutri7": "Difficulty chewing and swallowing",
  "smaNutri8": "Inhaling food or liquid into the lungs (aspiration)",
  "smaNutri9": "Gastrointestinal (GI) problems like constipation or diarrhea",
  "smaNutri10": "Gastroesophageal reflux disease (GERD), also known as acid reflux",
  "smaNutri11": "Low or high blood sugar",
  "smaNutri12": "You can speak to a Nutritional Specialist to manage SMA free of cost from your app.",
  "smaPhy1": "Physiotherapy options depend on the subtype and the symptoms that are present. It will largely depend on the severity of your condition and level of mobility. General guidance on techniques for SMA can include:",
  "smaPhy2": "Improving joint range of movement",
  "medicalManagement": "Medical Management of SMA",
  "medicalTitle": "Doctors can recommend multiple approaches that complement treatment to improve quality of life. These include therapies to manage:",
  "dayToday": "There may be different daily challenges when living with SMA, even after treatment. However, these strategies can help you get through each day with more confidence.",
  "respWeaknes": "Respiratory Muscle Weakness",
  "swallowing": "Swallowing Muscle Weakness",
  "progressive": "Progressive Spinal Curvature",
  "respSma1": "When the respiratory muscles weaken, air doesn’t move into and out of the lungs very well; there are subsequent adverse effects on general health. Portable, effective ventilation devices have created more options for newborns with SMA and, in some cases, have a greatly extended life.",
  "respSmaTitle1": "Non-Invasive Ventilation",
  "respSma2": "Air (usually environmental and not enriched with oxygen) is delivered under pressure through a mask or mouthpiece. This kind of system comes in many forms and can be used as many hours of the day and/or night as necessary. It can easily be removed for eating, drinking, and talking.",
  "respSmaTitle2": "Invasive Ventilation",
  "respSma3": "A surgical hole in the trachea, or windpipe, is created to deliver pressured air through a tube in the tracheostomy site. After a period of adjustment, it’s usually possible for people to eat, drink, and talk with a tracheostomy tube.",
  "swallowing1": "Sucking weakness can lead to dehydration and poor nutrition while swallowing weakness can lead to obstruction of the airway and respiratory infections from inhaled food or liquids (aspiration).\n\n\n They can be fed by alternative methods, such as a feeding tube, often called a gastrostomy tube or g-tube. A feeding tube is a small, flexible tube, about the diameter of a pencil, that allows liquid nutrition (homemade or commercially prepared) to enter the stomach directly, bypassing the mouth, throat, and esophagus.",
  "progressive1": "Weakness of the muscles of the back that generally support the flexible, growing spine can lead to scoliosis — a side-to-side curvature of the spine — or kyphosis, a forward curvature of the spine, or both. Some may even end up with \"pretzel\" types of curvatures that make it impossible to sit or lie down with comfort.\n\n\nThe permanent solution to spinal curvature is almost always spine-straightening surgery, which can be done if the childs respiratory status is good enough to withstand the surgery.",
  "smaNutri1": "Poor nutrition can worsen muscle weakness and limit growth for people with SMA. Nutrition experts have seen that a balanced diet provides many benefits to people with SMA, including:",
  "smaNutri2": "Improved growth and motor function",
  "zolgensmaSideEffect5": "Serious liver damage",
  "evrysdiDesc": "Evrysdi is the first oral medication approved for the treatment of SMA. It’s composed of a small molecule that modifies the amount of SMN protein made from the SMN2 gene. This, in turn, helps increase SMN protein levels available in the nervous system.\nIt is approved for use by individuals aged 2 months and older. The medication is taken orally once daily after a meal and given using an oral syringe.",
  "evrysdiSideEffect1": "You can talk with your child’s doctor about using Evrysdi to treat SMA. They can discuss the potential benefits and side effects of the treatment associated.",
  "evrysdiSideEffect2": "Joint aches and pains",
  "evrysdiSideEffect3": "Urinary tract infections",
  "evrysdiSideEffect4": "Fever",
  "evrysdiSideEffect5": "Diarrhea",
  "evrysdiSideEffect6": "Rash",
  "evrysdiSideEffect7": "Mouth ulcers",
  "evrysdiSideEffect8": "Additional side effects may also occur in infants with SMA taking this medication. These include:",
  "evrysdiSideEffect9": "Upper respiratory tract infections",
  "evrysdiSideEffect10": "Pneumonia",
  "smaManagMainDesc": "The management of SMA requires a broad multi-disciplinary approach which includes rehabilitation, spinal management, orthopedics, nutritional and gastrointestinal management. In addition, your doctor might recommend specific treatments to help manage symptoms or potential complications.",
  "dayToDay": "Day-to-Day-Management",
  "smaSideEffectDesc": "Although side effects are possible, your child’s healthcare provider will only recommend the medication if they believe the benefits outweigh the risk of side effects.10   Common known side effects include:",
  "smaSideEffectDesc1": "Increased risk of respiratory infection",
  "smaSideEffectDesc2": "Increased risk of bleeding complications",
  "smaSideEffectDesc3": "Kidney damage",
  "smaSideEffectDesc4": "Constipation",
  "smaSideEffectDesc5": "Vomiting",
  "smaSideEffectDesc6": "Headache",
  "smaSideEffectDesc7": "Back pain",
  "smaSideEffectDesc8": "Fever",
  "onasemnogeneDesc": "Zolgensma is a type of gene therapy in which a modified virus is used to deliver a functional SMN1 gene. People with SMA have a defect in this gene that usually codes for SMN protein. \n\nZolgensma is a one-time treatment administered through intravenous (IV) infusion. It is given only to infants with SMA under 2 years old.",
  "zolgensmaSideEffect1": "If your child’s doctor prescribes Zolgensma, they will need to order tests to monitor your child’s liver enzyme health before, during, and after treatment. Common known side effects include:",
  "zolgensmaSideEffect2": "Abnormally elevated liver enzymes",
  "zolgensmaSideEffect3": "Increased markers of heart muscle damage",
  "zolgensmaSideEffect4": "Vomiting",
  "type3Desc2": "People may experience muscle weakness that will get worse over time",
  "type3Desc3": "Many children with Type 3 SMA will learn to walk, but this ability will be lost over time as they progress into adolescence.",
  "type3Desc4": "Life expectancy is not usually affected",
  "type3Desc5": "Legs may be weaker than arms",
  "type4Desc": "Late-onset of the disease, usually after age 30. A mild form of SMA and, therefore, lifespan remains normal. Patients are able to achieve motor milestones and maintain their mobility throughout life.",
  "smaTreatmentDesc": "New therapies are improving the outlook for children and adults with SMA. Supportive therapy help manage symptoms and potential complications. Regular check-ups will allow the healthcare team to monitor their condition and assess how well their treatment plan is working. \n\n Currently, there are three therapies available for SMA:",
  "nusinersen": "Nusinersen",
  "spinraza": "(Spinraza)",
  "onasemnogene": "Onasemnogene abeparvovec-xioi",
  "zolgensma": "(Zolgensma)",
  "risdiplam": "Risdiplam",
  "evrysdi": "(Evrysdi)",
  "nusinersenDesc": "Nusinersen (Spinraza) is a medication designed to boost the production of an essential protein known as a  Survival motor neuron (SMN). People with SMA don’t produce enough of this protein on their own. As a result, the protein helps motor nerves survive. \n\nIf your child’s doctor prescribes Spinraza, they will inject the medication into the fluid surrounding your child’s spinal cord. They will start by giving four doses of the drug over the first couple of months of treatment. After that, they will administer one dose every 4 months.",
  "smaType1": "Type 1",
  "smaType2": "Type 2",
  "smaType3": "Type 3",
  "smaType4": "Type 4",
  "type1Desc1": "Develops in babies less than 6 months old and is life-limiting. 2,4 Few children survive beyond two years of age.",
  "type1Desc2": "Babies are often ‘floppy’ due to severe muscle weakness; they struggle to control their heads or lift their arms and legs.",
  "type1Desc3": "They may also struggle to breathe sufficiently on their own.",
  "type1Desc4": "Babies will never be able to sit unaided.",
  "type2Desc1": "Develops in children who are 7-18 months old, leading to muscle weakness. It may also shorten life expectancy.",
  "type2Desc2": "Children with SMA Type 2 will never be able to walk.",
  "type2Desc3": "As muscles weaken over time, some people may develop a curvature of the spine, called scoliosis",
  "type2Desc4": "Many will develop significant respiratory and breathing problems, as well as have problems swallowing",
  "type2Desc5": "Many achieve the ability to sit, but this ability will be lost over time",
  "type3Desc1": "Develops after 18 months of age and may not be evident until late childhood.",
  "sma": "Spinal Muscular Atrophy Cancer",
  "smaHeader": "Spinal Muscular Atrophy(SMA)",
  "understandingSMA": "Understanding SMA",
  "treatmentSMA": "Treatment for SMA",
  "managingSMA": "Managing SMA",
  "smadesc1": "What is Spinal muscular atrophy (SMA)?",
  "smadesc2": "Spinal muscular atrophy (SMA) is a genetic disease affecting the central nervous system, peripheral nervous system, and voluntary muscle movement (skeletal muscle). SMA involves the loss of nerve cells called motor neurons in the spinal cord and is a motor neuron disease.\n\nAlthough SMA is mainly diagnosed in childhood, it can affect people at any age, from childhood to adulthood. However, the earlier symptoms appear, the more severe the disease.",
  "smadesc3": "Why does it occur?",
  "smadesc4": "SMA is caused by a mutation of the survival motor neuron 1 (SMN1) gene, which leads to a deficiency of the SMN protein. This protein is found throughout the body and is essential to the function of nerves that control muscles and movement.\n\nThe body has two very similar genes that make SMN protein: SMN1 and SMN2.",
  "smadesc5": "Healthy individuals",
  "smadesc6": "have the SMN1 gene that can produce enough protein for the body to function normally.",
  "smadesc7": "Individuals with SMA",
  "smadesc8": "must rely on the ‘backup’ SMN2 gene, which produces insufficient amounts of functional SMN protein.",
  "smaTypes": "Types of SMA:",
  "smaTypesDesc": "Every person with SMA is different, but there are 4 main types of SMA, based on the age when symptoms first appear.",
  "LiverCancerDesc": "A healthcare team evaluates numerous conditions to determine the right treatment.The factors that define lung cancer treatment are:",
  "treatmentStrategie": "Treatment Strategies",
  "treatmentStrategieDesc": "After verifying all the above factors, a patient may receive one or more of the following treatments:",
  "sideEffectDesc": "Cancer treatments can sometimes be challenging, causing your physical and emotional health to go through ups and downs. It takes time to heal from the side effects altogether. However, various nutritional tips, physiotherapy and psychological counsellors are available to deal with these side effects. \n\nHere are some common and simple tips to deal with the side effects of cancer treatments:",
  "liverStages": "BCLC further classifies Liver Cancer into five stages",
  "liverStage1": "Early-stage disease and indicates that the tumour is less than 2cm..",
  "liverStage2": "Early-stage disease and liver may have a single tumour of any size or up to 3 tumours less than 3 cm in size..",
  "liverStage3": "Also known as the intermediate stage indicating many tumours in the liver.",
  "liverStage4": "Advanced stage disease indicating that cancer has been spread into blood vessels, lymph nodes, and distant organs.",
  "liverStage5": "Indicates severe liver damage that needs immediate medical attention.",
  "liverStageA": "Stage A",
  "liverStageB": "Stage B",
  "liverStageC": "Stage C",
  "liverStageD": "Stage D",
  "livermainDesc": "You can manage liver cancer with the help of suitable medication, diet, and physiotherapy. Apart from these, taking care of your mental and emotional health is also essential. It can support your treatment and help you feel better physically.",
  "liverCancerStage2": "BCLC System",
  "liverCancerStage1Desc": "Stands for Tumour, Nodes, Metastasis and is a commonly used cancer staging system. It helps us understand.",
  "tumor": "Tumor",
  "tumorDesc": "Size, number, and location of the tumour in the liver.",
  "nodes": "Nodes",
  "nodesDesc": "If cancer has spread into near by lymph nodes.",
  "metastasis": "Metastasis",
  "metastasisDesc": "Whether cancer cells have spread into distant lymph nodes, or other organs such as bones",
  "bclcDesc": "Stands for Barcelona Clinic Liver Cancer and is used to determine how well the liver is functioning, which the TNM system cannot do. It determines:",
  "bclcDesc1": "The size and number of tumours present in the liver.",
  "bclcDesc2": "The patients performance status including overall health and fitness.",
  "bclcDesc3": "The functionality of the liver- how well the liver is working, which is identified by the Child-Pugh score",
  "bclcStages": "BCLC further classifies Liver Cancer into five stages",
  "secondaryLiverDesc": "Originates somewhere else in the body and spreads into the liver. Breast, lung, stomach, and colon cancer may spread into the liver. Since these cancers do not primarily originate in the liver, they are known as secondary liver cancer. The treatment may depend on the origin of the cancer cells, the stage of cancer, and the spread of the cancer.",
  "LiverCancerHeader": "Liver Cancer Treatments",
  "primaryLiverSub1": "Hepatocellular carcinoma (HCC)",
  "primaryLiverSub1Desc": "HCC most commonly occurring liver cancer that originates in hepatocellular cells of the liver. HCC can either start as a large tumour in the liver or spread cancer nodules throughout the liver.",
  "primaryLiverSub2": "Intrahepatic cholangiocarcinoma\n(bile duct cancer)",
  "primaryLiverSub2Desc": "Begins at the cells that line the bile ducts outside the liver. Only 10% to 20% of liver cancers are bile duct cancer.",
  "primaryLiverSub3": "Angiosarcoma and Hemangiosarcoma",
  "primaryLiverSub3Desc": "Rare types of liver cancers, mostly originate from the cells outlining the blood vessels in the liver. This type of cancer tumour may grow quickly or spread widely, making it difficult to treat.",
  "primaryLiverSub4": "Hepatoblastoma",
  "primaryLiverSub4Desc": "The rarest type of liver cancer, usually occurring in children younger than 4 years old. Most patients suffering from Hepatoblastoma can be successfully treated with Chemotherapy or Surgery.",
  "liverCancerInfo": "The following section provides information only about Hepatocellular Carcinoma Cancer (HCC) which is the most commonly occurring liver cancer.",
  "liverCancerStages": "Stages of Liver Cancer",
  "CancerStage": "Liver Cancer Stages",
  "liverCancerstageDesc": "Staging of HCC depends on factors like the tumour location, spread, and severity. The lower the stage, the higher the chances of getting cured. It is important to determine the stage of cancer to decide on the right treatment. There are two types of cancer staging systems available for liver cancer.",
  "liverCancerStage1": "TNM System",
  "breastPhysiotherapy": "Physiotherapy",
  "breastPsychologicalSupport": "Psychological Support",
  "breastNutriDes1": "Prioritizing your mental health is equally as important as caring for your physical health while dealing with breast cancer. Talk to a mental health expert to find effective strategies that help you deal with confusing emotions. This service is available to you free of cost.",
  "liverCancerPhysioDesc1": "Prioritizing your mental health is equally as important as caring for your physical health while dealing with liver cancer. Talk to a mental health expert to find effective strategies that help you deal with confusing emotions. This service is available to you free of cost.",
  "liverCancerPhysioDesc": "A liver cancer diagnosis can be distressing and cause emotions of shock, anxiety, anger, sadness, and confusion. Along with the physical impacts of cancer, side effects of treatment, fear of recurrence, and changes to identity can aggravate mental health conditions. A mental health expert can help you manage these feelings. Here’s how sessions with a counsellor can help:",
  "liverCancerHeader": "Liver Cancer",
  "liverCancerUnderstand": "Understanding Liver Cancer",
  "liverTreatment": "Treatment for Liver Cancer",
  "liverManaging": "Managing Liver Cancer",
  "liverHeadersub1": "What is Liver Cancer?",
  "liverHeaderDesc": "Liver cancer is a type of disease when cancer cells/tumours originate in the liver. Cancerous cells form and start growing from the tissues of the liver.\n\nThe liver is primarily made of hepatocytes cells. It also has cells that line blood vessels and cells outlining bile duct tubes that carry bile from the liver to the gallbladder or intestines. Cancer may occur in any of the above cells, but most commonly in hepatocytes cells.",
  "liverCancerTypes": "Types of Liver Cancer:",
  "liverCancerTypes1": "Primary Liver Cancer",
  "liverCancerTypes2": "Secondary Liver Cancer",
  "breastBaseLoc5Desc": "The tumour is located only in the duct.",
  "breastBaseLoc6": "Invasive Ductal Carcinoma",
  "breastBaseLoc6Desc": "The cancer cells outgrow the duct.",
  "breastType2Header": "Types of Breast Cancer",
  "breastTypeHormoneHeader": "Types Based on Hormone\nReceptors",
  "breastTypeHor1": "Hormone Receptor-Positive (HR+)",
  "breastTypeHor1Desc": "Cancer cells have receptors for some female hormones.",
  "breastTypeHor2": "HER2-Positive",
  "breastTypeHor2Desc": "The growth of cancer cells is affected by the protein HER2.",
  "breastTypeHor3": "Triple-Negative Breast Cancer",
  "breastTypeHor3Desc": "Cancer cells do not have receptors for hormones or proteins.",
  "breastTreatment": "Treatment for Breast Cancer",
  "breastTreatmentDesc": "Doctors will recommend a series of options for your treatment depending on the stage of the disease.Each treatment has different ways, durations, and medication. Sometimes, doctors might combine more than one therapy to address the condition.",
  "breastSideEffectDesc": "Cancer treatments can sometimes be challenging, causing your physical and emotional health to go through ups and downs. It takes time to heal from the side effects altogether. However, various nutritional and dietary tips are available to deal with these side effects – speak to your nutritional counsellor to get customised diet plans.",
  "breastMainTitle": "Managing Breast Cancer",
  "breastMainDescription": "You can manage breast cancer with the help of suitable medication, diet, and physiotherapy. Apart from these, taking care of your mental and emotional health is also essential. It can support your treatment and help you feel better physically.",
  "breastStages4": "Stage 4",
  "breastStages4Desc": "Cancer has spread to other parts of the body.",
  "breastType1Header": "Types of Breast Cancer",
  "breastBaseLoc": "Types Based on Location",
  "breastBaseLoc1": "Lobular Carcinoma",
  "breastBaseLoc1Desc": "Growth of cancer cells from the lobules of the breasts.",
  "breastBaseLoc2": "Lobular Carcinoma in Situ (LCIS)",
  "breastBaseLoc2Desc": "Cancer cells grow only in lobules and risk developing invasive cancer in both breasts.",
  "breastBaseLoc3": "Invasive Lobular Carcinoma",
  "breastBaseLoc3Desc": "Cancer cells spread outside lobules.",
  "breastBaseLoc4": "Ductal Carcinoma",
  "breastBaseLoc4Desc": "Cancer cells grow from the ducts in the breasts.",
  "breastBaseLoc5": "Ductal Carcinoma in Situ (DCIS)",
  "breastTitle": "What is Breast Cancer?",
  "breastDesc": "Breast Cancer is a disease in which tissues containing milk glands grow out of control and can spread to nearby areas/organs. \n\nMilk-producing glands, the duct tubes carrying milk to the nipples and surrounding tissues, create breasts. The tumour is mainly associated with the milk glands and could be hard to detect.",
  "breastType": "Two Types of Breast Cancer:",
  "breastType1": "Types Based on Location",
  "breastType2": "Types Based on\nHormone Receptors",
  "breastStages": "Breast Cancer Stages",
  "breastStagesDesc": "There are four stages, starting from zero.If detected at stage 0 or 1, the survival chances are 90%. However, the survival rate could decrease as the cancer stage increases. These stages determine the severity and best possible cancer treatment.",
  "breastStages0": "Stage 0",
  "breastStages0Desc": "Found only inside the ducts or lobules. It has not spread to surrounding breast tissue, lymph nodes, or distant sites.",
  "breastStages1": "Stage 1",
  "breastStages1Desc": "Cancer is small and only in the breast tissue or might be found in lymph nodes close to the breast.",
  "breastStages2": "Stage 2",
  "breastStages2Desc": "Cancer is either in the breast, nearby lymph nodes, or both.",
  "breastStages3": "Stage 3",
  "breastStages3Desc": "Cancer has spread from the breast to lymph nodes close or the skin of the breast or the chest wall.",
  "orderDetailsText": "Order details",
  "orderRequestText": "Order Request Date",
  "yourApptFor": "Your Appointment for",
  "hasBeenApproved": "has been booked and sent for \napproval",
  "deleteAcc": "Delete Account",
  "sideEffectText": "Side Effects of Treatment",
  "tcHeader": "New Terms and Conditions",
  "tcDesc": "We have updated our terms and conditions.\nReview the changes to continue",
  "acceptTc": "Accept new terms",
  "BC": "Breast Cancer",
  "BCUnderstand": "Understanding Breast Cancer",
  "BCTreatment": "Treatment for Breast cancer",
  "BCManage": "Managing Breast cancer",
  "breastHeader": "Understanding Breast Cancer",
  "patientTest": "Patient testimonial",
  "doctorPrescription": "Doctors prescriptiopn",
  "uploadDocument": "upload document",
  "feedbackGiven": "Feedback Given",
  "shareFeedback": "Share Feedback",
  "feedBackDes": "How would you rate your overall \nsigning in experience with Roche ?",
  "feedBackDesOrder": "How would you rate your overall \nexperience of ordering FOC with Roche ?",
  "questionnaireAlert": "Please make sure have given rating for all questions",
  "feedbackSucessfull": "Feedback Successful !",
  "requestSent": "Request sent",
  "requestSentDesc": "Your service request is sent for approval",
  "feedBackDes2": "Your feedback has been successfully submitted. Thank you so much !",
  "yourText": "Your",
  "reviewText": "booking session is booked and is being reviewed",
  "reschduleText": "session is booked for the below dates is being reviewed.",
  "afternoon": "Afternoon",
  "evening": "Evening",
  "balanceDiet": "Balanced diet",
  "dailyDiet": "Daily diet",
  "reviewSucessfull": "Review sucessfull",
  "lungCancer": "Lung cancer",
  "breastCancer": "Breast cancer",
  "liverCancer": "Liver cancer",
  "hemophilla": "Hemophilla",
  "spinal": "Spinal Muscular Atrophy (SMA)",
  "bookLet": "Booklet",
  "phsioInsert": "PHSIO Insert",
  "nutritional": "Nutritional Insert",
  "videoOnDisease": "Video on disease",
  "helpful": "Helpful videos",
  "viewPsychoSocialDesc": "Your Physio-social counselling booking session is booked for the below dates is being reviewed.",
  "viewDiagnosticDesc": "Your Diagnostic support booking session is booked for the below dates is being reviewed.",
  "submitDocDescription": "Please note that the Doctor Prescription and Coupon are mandatory to book a slot. If you don't have them click on \"Skip\" to proceed further or click on \"Upload\" if you have it.",
  "couponDescription": "Please note that the coupon is mandatory to book a slot. If you don't have it click on \"Skip\" and proceed further or click on \"Upload\" if you have it.",
  "uploadPRescriptionDesc": "Please note that the Doctor Prescription is mandatory to book a slot. If you don't have it click on \"Skip\" and proceed further or click on \"Upload\" if you have it",
  "docSuccessText": "Submitted Sucessfully",
  "docSuccessDesc": "Your request for the Diagnostic support has been submitted successfully",
  "note": "Note !",
  "uploadInvoiceTitle": "Upload Invoice",
  "uploadInvoiceDesc": "Paid Invoice and Patient Summary is Mandatory to process your FOC Medicine, if you don’t have click on “skip”, if you have it click on “Upload”",
  "skip": "Skip",
  "alertDiagnostic": "Service cannot be booked",
  "alertReview": "Booking is in review",
  "booksummaryDate": "Date",
  "morning": "Morning",
  "imagingTests": "Imaging tests",
  "biopsyTests": "Biopsy tests",
  "diseaseAwareness1": "Disease Awareness",
  "diagnosticSubText": "Health professional with special training in \nnutrition helps people make healthy food \nchoices and form healthy eating habits.",
  "sucessEnrollText": "After sucessful enrolment, your free medicine dates, Therapy dates, value added services will appear in your calendar after approval.",
  "diagnostic": "Diagnostic Support",
  "enrollTitle": "Enroll to the Blue \nTree program",
  "enrollButton": "Enroll",
  "diagnosticEnroll": "Health professional \nwith special training \nin nutrition helps \npeople make healthy \nfood choices",
  "nutritionEnroll": "A process by which a \nhealth professional \nhelps people make \nhealthy food choices",
  "physiotherapyEnroll": "Physiotherapists help \npeople affected by \ninjury, illness or disability through \nmovement & exercise",
  "psychoEnroll": "A service provided by a \nskilled professional \ncounselor to an \nindividual, family, \nor,group",
  "viewAppointment": "View Appointment",
  "viewNutritionDesc": "Your Nutritional counselling booking session is booked for the below dates is being reviewed.",
  "viewPhysiotheraphyDesc": "Your Physiotherapy booking session is booked for the below dates is being reviewed.",
  "physiotheraphyDesc": "A process by which a health professional with special training in nutrition helps people make healthy food choices and form healthy eating habits. Its is a two-way interaction through which a patient and the member of the medical team interpret the results of a nutritional assessment, identify patient nutritional problems, needs and goals, A process by which a health professional with special training in nutrition helps people make healthy food choices and form healthy eating habits. Its is a two-way interaction through which a patient and the member of the medical team interpret the results of a nutritional assessment, identify patient nutritional problems, needs and goals",
  "breathingExercises": "Breathing exercises",
  "movementPattern": "Movement pattern training",
  "relaxationExercises": "Relaxation exercises",
  "neuromuscularExercise": "Neuromuscular Exercise",
  "psychoSocial": "Psycho-Social Counselling",
  "psychoSocialDesc": "A process by which a health professional with special training in nutrition helps people make healthy food choices and form healthy eating habits. Its is a two-way interaction through which a patient and the member of the medical team interpret the results of a nutritional assessment, identify patient nutritional problems, needs and goals, A process by which a health professional with special training in nutrition helps people make healthy food choices and form healthy eating habits. Its is a two-way interaction through which a patient and the member of the medical team interpret the results of a nutritional assessment, identify patient nutritional problems, needs and goals",
  "socialWellbeing": "Social wellbeing",
  "spiritualWellbeing": "Spiritual wellbeing",
  "culturalWellbeing": "Cultural wellbeing",
  "emotionalWellbeing": "Emotional wellbeing",
  "diagnosticSupportDesc": "A process by which a health professional with special training in nutrition helps people make healthy food choices and form healthy eating habits. Its is a two-way interaction through which a patient and the member of the medical team interpret the results of a nutritional assessment, identify patients nutritional problems, needs and goals, A process by which a health professional with special training in nutrition helps people make healthy food choices and form healthy eating habits. Its is a two-way interaction through which a patient and the member of the medical team interpret the results of a nutritional assessment, identify patients nutritional problems, needs and goals",
  "physicalTests": "Physical tests",
  "laboratoryTests": "Laboratory tests",
  "assessment": "Assessment",
  "action": "Action",
  "descriptionTitle": "Description",
  "readLessText": "Read less",
  "dyslipidemiaTitle": "Dyslipidemia diet",
  "hepaticTitle": "Hepatic encephalopathy",
  "ketogenicTitle": "Ketogenic diet",
  "dashDiet": "Dash diet",
  "bookAppointmentTitle": "Book Appointment",
  "uploadPrescription": "Upload Prescription",
  "nutritionalCounselling": "Nutritional counselling",
  "nutritionalDesc": "A process by which a health professional with special training in nutrition helps people make healthy food choices and form healthy eating habits. Its is a two-way interaction through which a patient and the member of the medical team interpret the results of a nutritional assessment, identify patient nutritional problems, needs and goals,member of the medical team interpret the results of a nutritional assessment, identify patient nutritional problems, needs and goalsa nutritional assessment, identify patient nutritional problems, needs and goals,member of the medical team interpret the results of a nutritional assessment, identify patient, A process by which a health professional with special training in nutrition helps people make healthy food choices and form healthy eating habits. Its is a two-way interaction through which a patient and the member of the medical team interpret the results of a nutritional assessment, identify patient nutritional problems, needs and goals,member of the medical team interpret the results of a nutritional assessment, identify patient nutritional problems, needs and goalsa nutritional assessment, identify patient nutritional problems, needs and goals,member of the medical team interpret the results of a nutritional assessment, identify patient",
  "physiotheraphy": "Physiotheraphy",
  "giveFeedback": "Give Feedback",
  "download": "Download",
  "feedback": "Feedback",
  "feedbackDescription": "How satisfied were you with your experience",
  "shareReview": "Share your review",
  "placeHolder": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
  "selectDate": "Select Date",
  "bookAppointment": "Select a date to reserve a time slot for",
  "cancelAppointmentText": "Why do you wish to cancel the appointment",
  "rescheduleAppointmentText": "Why do you wish to reschedule the appointment",
  "commentHere": "Comment here",
  "okay": "Okay",
  "cancelSuccess": "Your request has been cancelled sucessfully",
  "analysis": "Analysis",
  "disbursedAmount": "Disbursed Amount",
  "referenceNumber": "Reference Number",
  "beneficiaryNumber": "Beneficiary Name",
  "beneficiaryAccountNumber": "Beneficiary Account Number",
  "trackRequest": "Track Request",
  "intrested": "I'm Intrested",
  "requestStatus": "Request status",
  "bookingHistory": "Booking History",
  "upcoming": "Upcoming",
  "completed": "Completed",
  "cancelled": "Cancelled",
  "nutritionCounselling": "Nutritional Counselling",
  "diagnosticSupport": "Diagnostic Support",
  "physiotherapy": "Physiotherapy",
  "physioSocio": "Psycho-Social Counselling",
  "slotTitle": "Slot sent for approval",
  "slotSubTitle": "Your appointment for Psycho-Social \nCounselling has been booked and sent for \napproval",
  "confirmationTitle": "Confirmation",
  "confirmationSubTitle": "Your appointment for diagnostic \ncounselling has been sucessfully booked",
  "bookSummary": "Booking Summary",
  "meetingLink": "https://bit/y.zoom.us",
  "reschedule": "Reschedule",
  "date1": "Date",
  "timeSlot": "Time slot",
  "meetingTitle": "MeetingLink",
  "timeSlotTitle": "Slot",
  "selectTime": "Select Slot",
  "valueAddedServices": "Value-Added Services",
  "seeMore": "See more",
  "loanAmount": "Loan Amount",
  "introLine3": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor.",
  "introLine4": "Be a part of India's largest patient support community",
  "introLine6": "24x7",
  "introLine8": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor.",
  "cardDescription": "Personal details, Addresses, Caregiver details, etc",
  "cardDocDescription": "Invoices, ID proofs, Prescriptions, etc.",
  "cardSetDescription": "Change language and \ntrack order history",
  "documentDownloaded": "Document Downloaded Successfully",
  "donwloadError": "Download Error Please try after some time.",
  "LastTherapyDate": "Last Therapy date",
  "enrolmentRejected": "Enrolment Process Rejected",
  "rejectedDesc": "We could not process your request. Please visit the help section for more details.",
  "underReview": "Under Review",
  "reviewSubTitle": "Your appointment for diagnostic \ncounselling is under review",
  "dispatchAddressLabel": "Dispatch Address",
  "careGiverAddressLabel": "Caregiver Address",
  "otherLabels": "Other details",
  "checkBoxLabel1": "I’ve read and I understand the above Terms & \nconditions",
  "checkBoxLabel2": "I give my consent by accepting the above \nInformation by ticking on the check box",
  "login": "Login",
  "readFullContent": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. In nibh mauris cursus mattis. In eu mi bibendum neque. Purus in massa tempor nec feugiat nisl pretium fusce id. eo integer. Risus pretium quam vulputate dignissim suspendisse in est.",
  "readMore": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. In nibh mauris cursus mattis. In eu mi bibendum neque. Purus in massa tempor nec feugiat nisl pretium fusce id. Enim blandit volutpat maecenas volutpat blandit aliquam. Nascetur ridiculus mus mauris vitae ultricies leo integer. Risus pretium quam vulputate dignissim suspendisse in est.",
  "terms1": "I’ve read and I understand that lorem ipsum dolor sit amet, consectetur adipiscing elit.",
  "terms2": "I give my consent to lorem ipsum dolor sit amet, consectetur adipiscing elit.",
  "docName": "Aadhaar card-Jhon Doe.pdf hdksd fhkshgf'",
  "time": "21 May 2022, 12:12 pm",
  "intoLine1": "Welcome to",
  "introLine2": "The Blue Tree Program!",
  "inputEmptyEmailError": "Please enter Email",
  "inputValidEmailError": "Please enter valid Email",
  "inputEmptyGenderError": "Please select valid Gender",
  "inputEmptyDOBError": "Please select valid Date of Birth",
  "skipLabelWithIcon": ">> Skip for Now",
  "fillMandatoryFields": "Please fill the mandatory details first.",
  "addDetails": "+ ADD DETAILS",
  "Settings": "Settings",
  "uploadProgress": "100%",
  "textLabel": "Upload documents to get yourselves enrolled for the TBT Program.\nWe will be reviewing your documents and if needed, we shall reach \nout to you.",
  "mainTitle": "Managing Lung Cancer",
  "mainTextDescription": "To get the FOC Vials from Lorem, we would like to know your \n Address(s), Caretaker details, etc. lorem ipsum dolor sit amet, \nconsectetur adipiscing elit.",
  "seeWhy": "See why?",
  "personalInfoLabel": "Personal Info",
  "addressLabel": "Address",
  "addressDetails": "Akshay nahar 1st block 1st cross, rammurthy nagar,mumbai - 416008",
  "bendamustine": "Bendamustine (Levact)",
  "date": "PAP (2) Date",
  "confirmOrder": "Place Order Request",
  "addDispatchTitle": "The FOC vials will be delivered in the above address. You want us to deliver the products at a different address?",
  "orderIdTitle": "Order ID :",
  "enterOTP": "Enter OTP",
  "inputEmptyFirstNameError": "Please enter first name",
  "inputValidFirstNameError": "Please enter valid First name",
  "inputValidMiddleNameError": "Please enter valid Middle name",
  "inputValidLastNameError": "Please enter valid Last name",
  "inputEmptyLasttNameError": "Please enter last name",
  "inputEmptyMobileNumberError": "Please enter Mobile Number",
  "expTimeLabel": "23: 45: 00 hr",
  "myTherapy": "My Therapy",
  "patientName": "Hi, Patient Name",
  "videoTitle": "How to lorem ipsum dolor sit amet?",
  "vialStatus": "Vial Status",
  "subText": "Bleeding is infrequent",
  "ExpETA": "23: 45: 00 hr",
  "outForDelivery": "Out for Delivery.",
  "tractDelivery": "Track delivery",
  "expDelivery": "Expect the delivery by:",
  "selectedDate": "Selected Date",
  "selectedTime": "Selected Time",
  "levact": "Bendamustine (Levact)",
  "infusionDateTitle": "Infusion Date",
  "lasteDate": "Last date to buy",
  "add": "add",
  "check": "check",
  "primaryPhysician": "Primary treating physician",
  "order": "Order History",
  "logout_alert": "Do you want to logout ?",
  "delete_alert": "Do you want to delete this account ?",
  "logoutAlert": "Are you sure you want to logout ? We cant notify of new updates",
  "deleteAlert": "Are you sure you want to delete this account ? We cant notify of new updates",
  "cancel": "Cancel",
  "weAreProcessing": "We are processing your \nenrolment.",
  "subTitle": "Kindly wait till lorem ipsum dolor sit amet, consectetur adipiscing elit.",
  "subTitleLabel": "Sit back and relax, we will react out to you for lorem ipsum dolor sit amet, consectetur adipising elit.",
  "expectedLabel": "Expected to get \napproved in :",
  "hospital": "Hospital/Clinic",
  "cluster": "Cluster",
  "physicianError": "Please Select Physician",
  "physicianEmailError": "Please enter physician email address",
  "selectHospital": "Please select hospital/clinic",
  "validateEmail": "Enter valid email address",
  "refDrName": "Please enter reffering doctors name",
  "stateRequire": "Please select the state",
  "clusterEmpty": "Please enter cluster",
  "search": "Search",
  "alert": "Profile Updated Successfully.",
  "phoneCode": "+91-",
  "personalInfo": "Personal Information",
  "name": "Name",
  "uploadLabel": "Take a photo",
  "uploadLabel2": "Choose photo from library",
  "uploadLabel3": "Choose a document",
  "uploadLabel4": "Cancel",
  "uploaded": "Uploaded:",
  "additionalDocumentLabel": "Want to upload any additional documents?",
  "uploadedOn": "Uploaded on:",
  "docAadhaarTitle": "Aadhaar card-John Doe.pdf",
  "docDate": "21 May 2022, 12:12 pm",
  "docStatus": "Uploaded",
  "suceessDescription": "We are reviewing your mandatory documents. \nWe will contact you if anything futher is \nneeded from your side.",
  "successCard": "Meanwhile, your profile is\nincomplete. We need to receive more\ninformation about Hospital Details to start your enrollment and address details to deliver your FOC Medicines after your enrollment.",
  "physicianTitle": "Primary treating physician",
  "physicianEmail": "Primary Physician's email",
  "drName": "Reffering doctors name",
  "inputValidError": "Please enter valid mobile number",
  "serverError": "Please check your internet connectivity and try agin after some time.",
  "mobileNumber": "Mobile",
  "mobile": "Mobile",
  "number": "Number",
  "enrollText": "Enter Mobile Number to enroll to The Blue Tree Program",
  "mobileNotificationMessage": "You will receive SMS Notifications regarding the enrollment and order updates",
  "myID": "My ID:",
  "description": "Welcome to your account. You can check the details of your profile,documents and settings here.",
  "profiledescription": "Personal details, Addresses, Caregiver details, etc",
  "myJournal": "My journal",
  "docIdDescription": "Invoices, ID proofs, Prescriptions, etc.",
  "journalDescription": "Symptoms, Side effects, Medicine infusion, personal writings, etc.",
  "text": "Lorem ipsum dolor sit amet, \n consecture adipiscing elit, \n sed do eiusmod tempor \n incididunt ut labore et \n dolor manga aliqua.",
  "textInputLabel1": "jpeg, pdf, heic, png",
  "textInputLabel2": "20 MB",
  "orderDescription": "Your can request your FOC order medicine as per the below calendar dates",
  "orderMedicine": "Order medicine",
  "ETAProcess": "Your Medicine is requested",
  "orderPlacedSuccess": "Your request for medicine is approved successfully",
  "welcomeDashboard": "welcome dashboard",
  "enrolmentProceed": "enrolment proceed",
  "enrolmentApproved": "enrolment approved",
  "orderProceed": "order proceed",
  "tbtApproved": "TBT approved",
  "orderSuccess": "order placed",
  "howEnrollProcess": "How the Enrolment \nProcess is done?",
  "viewAll": "View All",
  "items": "Items",
  "uploadOptDoc": "Upload mandatory and optional Documents",
  "inputEmptyError": "Please enter mobile number",
  "medicineName": "Bendamustine (Levact)",
  "lastDateLabel": "Last date to buy",
  "infusionDateLabel": "Infusion on",
  "infusionDate": "Infusion Date",
  "lastDate": "30th April 2022",
  "etaDate": "ETA :",
  "to": "MUM",
  "from": "PUN",
  "treatmentDesc": "Your Enrolment has been approved and below is the calender with all the FOC Dates available to request to order the medicine",
  "nextInfusionLabel": "Your next infusion is expected to be on",
  "expectedDate": "May 4th, 2022",
  "ETADes": "We are processing your enrolment and it will be completed within 1 hour",
  "ETAOrderDes": "will update you once it is reviewed and approved for delivery",
  "ETA": "ETA :",
  "orderSuccessDes": "Thanks for joining us! \nYou have made the right decision, now let us \nassist you in your journey towards wellness.",
  "videoText": "About the TBT Program Lorem ipsum dolor sit amet conse",
  "flatListLabel": "Understanding is so important.",
  "seeAll": "See all",
  "helpFlatListLabel": "Help / Guidelines.",
  "imageLabel": "There are similar stories to yours.",
  "userName": "Hi John!",
  "homeOtherLabel": "Other",
  "servicesLabel": "Services",
  "servicesSubLabel": "The recommended services are prescribed by your physician lorem ipsum dolor sit amet.",
  "programDescription": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
  "calendarSubText": "Your calendar can be viewed, \nonce the enrolment process is \ncompleted",
  "uploadDoc": "Upload Mandatory Documents",
  "medicine1Title": "Medicine name",
  "medicine2Title": "Medicine name",
  "editHocEmail": "Primary physician’s email",
  "editHocSuccessTitle": "Successfully completed \nthe profile!",
  "editHocSuccessDes": "We are reviewing your profile. We will contact \nyou if anything further is needed from \nyour side.",
  "editHocSuccessCard": "After sucessful enrolment,your \nfree medicine dates, Therapy \ndates, and more are marked in \nyour calendar which will appear after approval",
  "goToHome": "Go to Home",
  "editOtherDetTitle": "Other",
  "editOtherDetAlert": "Profile Updated Successfully",
  "OtherClusterLabel": "Cluster",
  "SourceLabel": "Source of Purchase",
  "genderTitle": "Personal\ninformation",
  "genderDescription": "Lorem ipsum dolar sit amet, consectetur adipiscing elit, set do eiusmod tempor.",
  "homeTitle": "Welcome to",
  "BlueTreeLabel": "The Blue Tree Program",
  "thankYouLabel": "Thanks for joining us!",
  "homeDescription": "You have made the right decision, now let us assist you in your journey towards wellness.",
  "careGiverAddressTitle": "Edit Care Giver Address",
  "careGiverAddressAlert": "Profile Updated Successfully",
  "careGiverInfoTitle": "Edit Care Giver Details",
  "careGiverInfoAlert": "Profile Updated Successfully",
  "editCurrentAddressTitle": "Edit Current Address",
  "editCurrentAddressAlert": "Profile Updated Successfully",
  "editDispatchAddressTitle": "Edit Dispatch Address",
  "editDispatchAddressAlert": "Profile Updated Successfully",
  "GenderInfoAlert": "Profile Updated Successfully",
  "editHocTitle": "HCO Details",
  "hospitalLabel": "Hospital/Clinic",
  "clusterLabel": "Cluster",
  "primaryTreatLabel": "Primary treating physician",
  "referringDocLabel": "Referring doctors name",
  "editHocAlert": "Profile Updated Successfully",
  "libraryUploadLabel": "Choose photo from library",
  "documentUploadLabel": "Choose a document",
  "cancelUploadLabel": "Cancel",
  "uploadTitle": "Upload",
  "mandatory": "Mandatory",
  "documentDescription": "",
  "docDescription": "See all your documents related \nto the entire journey ,with the \nBlue Tree Program",
  "cuurentAddressLabel": "Current Address",
  "pinCodeLabel": "PIN",
  "dispatch": "Dispatch",
  "addressInstruction": "The FOC vials will be delivered in the above address. You want us to deliver the products at a different address?",
  "inputEmptyAddressError": "Please enter Address",
  "inputEmptyPinError": "Please enter PIN",
  "inputValidAddressError": "Please enter valid Address",
  "inputValidPinError": "Please enter valid 6 digits PIN",
  "careGiverDispatch": "Dispatch",
  "mobileTitle": "Mobile",
  "inputEmptyFullNameError": "Please enter full name",
  "inputEmptyMobileError": "Please enter mobile number",
  "inputValidFullNameError": "Please enter valid full name",
  "inputValidStateError": "Please select State",
  "inputValidPrimaryDoctorError": "Please select Primary Doctor",
  "inputValidHospitalError": "Please select Hospital/Clinic",
  "inputValidMobileError": "Please enter valid mobile number",
  "documentsTitle": "TBT Documents",
  "documentsDescription": "Upload documents to get yourselves enrolled for the TBT Program. \nWe will be reviewing your documents and if needed, we shall reach\n out to you.",
  "photoUploadLabel": "Take a photo",
  "orderDelivery": "Order is out for delivery",
  "orderDev": "Order Delivered",
  "viewMore": "View more",
  "alertTitle": "Alerts",
  "orderProcess": "Your order is under process",
  "orderIsOnWay": "Your order is on its way",
  "orderHasDelivered": "Your order has been delivered",
  "nextFocDate": "Your next FOC Date is at",
  "orderRequestDate": "Order request date",
  "consentTitle": "I give consent to use this number to contact \nme by calling or send SMS.",
  "confirm": "Confirm",
  "orderOnTheWay": "order on the way",
  "caregiver": "Caregiver",
  "details": "Details",
  "orderDetails": "Order details",
  "orderId": "Order ID",
  "orderLabel": "Order ID :",
  "orderDate": "Order Date",
  "orderDateTitle": "Order Date",
  "deliveryDate": "Delivery Date",
  "itemsInOrder": "Items in you order",
  "continue": "Continue",
  "orderPlacedSucc": "Order Request Placed Successfully",
  "deliveryInformation": "Delivery Information",
  "orderDateLabel": "Order placed on :",
  "orderPlaced": "Order is placed",
  "orderApproved": "Order Request Placed Sucessfully",
  "requestMedicine": "Request Medicine",
  "uploadDocumentsTitle": "Upload \nDocuments",
  "orderList": "Order List",
  "medicine": "Medicine Details",
  "RequestRaisedDate": "Request Raised Date",
  "careGiverAddress": "Address",
  "uploadInvoice": "Upload Invoice",
  "uploadInfusionSummary": "Upload Infusion Summary",
  "orderConfirmation": "Order \nConfirmation",
  "confOrder": "Confirm Order",
  "orderSummary": "Order Summary",
  "orderSucess": "Order Placed Sucessfully",
  "approveDoc": "Your Documents are Approved",
  "patientProfile": "Your patient Profile",
  "treatmentSchedule": "Treatment Schedule",
  "treatmentDescription": "Your enrolment has been approved and below is the calender with all the FOC dates available to order your medicines",
  "therapyExpDate": "Your next therapy is expected to be on",
  "medicineNameTitle": "Medicine name",
  "medicineLabel": "Medicine name",
  "treatmentMedicineLabel": "Medicine name",
  "therapyDate": "Therapy Date",
  "therapyPaid": "Paid therapy date",
  "focDate": "FOC Dates",
  "purchaseDate": "Paid purchase Dates",
  "todayDate": "Today's date",
  "howRequestMedicine": "How to Request \nyour Medicine?",
  "reminder": "Send reminder",
  "additionalService": "Additional Services",
  "enrolmentTitle": "Your Enrolment to The Blue Tree Program is Approved",
  "orderTitle": "Your Enrolment to The Blue Tree Program is Approved",
  "orderFOCDates": "Your can Place your FOC med order as per the below calendar dates",
  "orderMedicines": "Order Medicines",
  "OrderProcess": "Your Order is Under Process",
  "trackOrder": "Track Order",
  "reviewDoc": "We are reviewing your Documents.",
  "medicineOrder": "Your medicine is on its way",
  "expectedDelivery": "Expected to get Delivered in",
  "label4": "Scan or capture a picture of the filled \n document",
  "label5": "Upload it here",
  "downloadTitle": "Download",
  "remove": "Remove",
  "preview": "Preview",
  "uploadMore": "Upload more",
  "successTitle": "Successfully uploaded \nthe mandatory \ndocuments!",
  "profile": "Go to profile",
  "copy": "Copy",
  "share": "Share",
  "pendinginfo": "Pending information",
  "cardDocTitle": "My documents",
  "hospitalsLabel": "Doctor & Hospital Details",
  "editLabel": "Edit",
  "patientDocForm": "Patient Doctor consent form",
  "docPrescription": "Doctor Presciption",
  "upload": "Upload document",
  "uploadOptionalDocuments": "Upload optional documents",
  "docKYC": "KYC Documents",
  "idProofPatient": "ID proof for only reimbursed patients",
  "vialInfo": "Vial purchase information",
  "hcpLetter": "HCP Letter",
  "diagnosticTest": "Diagnostic test Report",
  "formats": "Supported formats:",
  "size": "Maximum size:",
  "docTitle": "Don't have this\ndocument with you?",
  "instructionTitle": "Follow these steps after downloading\nthe document",
  "label1": "Download this document from here",
  "label2": "Take a print of the downloaded \n document",
  "label3": "Fill in the details to the physical \n document",
  "more": "More",
  "uploadDocuments": "Upload mandatory documents",
  "seeDocuments": "See documents",
  "completeProfile": "Complete your patient profile",
  "seeProfile": "See profile",
  "calendarHeader": "My Calendar",
  "docVerifiedAlert": "Once your documents are verified, your calendar will appear here.",
  "howToUploadDocuments": "How to Upload\n documents?",
  "programLabel": "Rehabilitation program",
  "seeDetails": "See details",
  "mentalHealth": "Mental health experts",
  "financial": "Financial assistance",
  "title": "ID Proof",
  "pending": "Pending",
  "view": "View sample",
  "needAssistance": "Need assistance?",
  "requestHelp": "Request help",
  "myAccount": "My Account",
  "myProfileTitle": "My Profile",
  "myProfile": "My profile",
  "myDocuments": "My Documents",
  "cardSetTitle": "My Settings",
  "drRecommendation": "Doctor's Recommendation",
  "drAssignedService": "Doctor Assigned Services",
  "mySettings": "My settings",
  "language": "Language Preference",
  "logout": "Logout",
  "ETATitle": "We are Processing your Enrolment",
  "ETATitle1": "We are Processing your enrolment",
  "estimatedTime": "Estimated time of arrival",
  "expectedApprove": "Expected to get \napproved in:",
  "Expected": "Expected to get",
  "approve": "approved in:",
  "fullNameLabel": "Full name",
  "relationship": "Relationship",
  "checkBoxLabel": "Address same as mine",
  "addAddress": "Add address",
  "finishProfile": "Finish Profile",
  "termsandconditions": "Terms and Conditions & Consent",
  "upateTerms": "T&C last updated on",
  "summary": "Summary",
  "readMoreText": "Read more",
  "readFull": "Read full",
  "read": "Read full >",
  "profileSub": "Submit Profile",
  "loadingexp": "Loading your Experience",
  "optimising": "Optimising",
  "gender": "Gender",
  "other": "Others",
  "dobLabel": "Date of Birth",
  "addresses": "Addresses",
  "addressLabel1": "Address line 1",
  "addressLabel2": "Address line 2",
  "stateLabel": "State",
  "cityLabel": "City",
  "country": "Country",
  "pinCode": "Pincode",
  "addAddressLabel": "Add dispatch address",
  "careGiverDetails": "Caregiver details",
  "careGiverDetailsLabel": "Caregiver details",
  "skipLabel": ">> Skip for Now",
  "label": "Mobile Number",
  "enterMobileNumber": "Enter Mobile Number",
  "consentTitleNew": "I give consent to use this number to contact me over Call, WhatsApp or SMS",
  "back": "Back",
  "verifyOTP": "Verify OTP",
  "enterOTPToVerify": "Enter OTP Received on your Mobile To Verify",
  "dontReceive": "Didn't receive?",
  "resendOTP": "Resend OTP",
  "personalInfoTitle": "Profile \nInformation",
  "profileDescription": "Please Enter Your Basic Profile Information to start your journey into The Blue Tree Program",
  "careGiverTitle": "Personal information",
  "personalTitle": "Personal Information",
  "firstNameLabel": "First name",
  "middleNameLabel": "Middle name",
  "lastNameLabel": "Last name",
  "email": "Email",
  "Malayalam": "മലയാളം",
  "Telugu": "తెలుగు",
  "Odia": "ଓଡ଼ିଆ",
  "Bengali": "বাংলা",
  "Assamese": "অসমীয়া",
  "TherapyAlert": "Therapy alert",
  "DeliveryAlert": "Delivery alert",
  "DocumentAlert": "Document alert",
  "CompleteProfile": "Complete Profile",
  "TrackDelivery": "Track delivery",
  "EmptyList": "We have no updates. \n please check again later.",
  "welcomeTitle": "Welcome to \nThe Blue Tree Program",
  "introLine5": "The Blue Tree community",
  "introLine7": "Help and Support",
  "select": "Select Language",
  "confirmAndProceed": "Confirm and Proceed",
  "hello": "Hello",
  "Hindi": "Hindi",
  "Tamil": "Tamil",
  "English": "English",
  "Kannada": "Kannada"
}

const App = (props: Props) => {
  useEffect(() => {
    (async () => {
      // const result = await translate(`I'm fine.`, { tld: "com", to: "hi", });
      // console.log('@TRANSLATED STRING...', result)
      for (let key in data) {
        // if (data.hasOwnProperty(key)) {
        console.log('@1...', data[key])
        data[key] = await translate(data[key], { tld: "com", to: "hi", })
        console.log('@2...', data[key])
        // }
      }
      console.log('@FINAL...', data)
    })()
  }, [])
  return (
    <View>
      <Text>App</Text>
    </View>
  )
}

export default App

const styles = StyleSheet.create({})